version: '3'

# 自定义网桥
networks:
  nt:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  server:
    # build: ./
    container_name: kserver
    image: kokota/knode
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    networks:
      nt:
        ipv4_address: 10.5.0.2
  redis:
    container_name: kredis
    image: redis
    ports:
      - '6379:6379'
    networks:
      nt:
        ipv4_address: 10.5.0.3
