version: '3'

services:
  jenkins:
    container_name: kjenkins
    image: jenkinsci/blueocean
    restart: always
    user: root
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./:/home
      - /var/run/docker.sock:/var/run/docker.sock
