version: '3'

services:
  jenkins:
    container_name: kjenkins
    image: jenkinsci/blueocean
    privileged: true
    restart: always
    user: root
    ports:
      - 8080:8080
    volumes:
      - ./:/home
      - ./home/jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/user/bin/docker
